trigger:
  branches:
    include:
      - main

pool:
  name: 'SelfHostedPool'

steps:
- checkout: self
  displayName: 'Checkout code'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Setup Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build:webpack
  displayName: 'Build the shell container app'

- script: az storage blob upload-batch --account-name $(AZURE_STORAGE_ACCOUNT) --account-key $(AZURE_STORAGE_KEY) -s dist -d $web --overwrite
  displayName: 'Upload Shell app dist to $web'
